[workspace]
members = [
    "syntaxdot-encoders",
    "syntaxdot-tokenizers",
    "syntaxdot-summary",
    "syntaxdot-transformers",
    "syntaxdot",
    "syntaxdot-cli",
    "syntaxdot-tch-ext"
]

[patch.crates-io]
tch = { git = "https://github.com/LaurentMazare/tch-rs.git" }